=== olivergondza/MapFilter_TreePattern/tests/new.sources/TreePattern053.dtd
<!ENTITY % common.elements "all|one|opt|some|alias|attr|node_attr|key_attr">
<!ENTITY % common.attrs
   "assert              CDATA   #IMPLIED
    flag                CDATA   #IMPLIED
    forValue            CDATA   #IMPLIED
    attachPattern       CDATA   #IMPLIED"
>
<!ENTITY % attr.attrs
   "attr                CDATA #IMPLIED
    default             CDATA #IMPLIED
    existenceDefault    CDATA #IMPLIED
    validationDefault   CDATA #IMPLIED
    valuePattern        CDATA #IMPLIED
    valueReplacement    CDATA #IMPLIED
    existenceAssert     CDATA #IMPLIED
    validationAssert    CDATA #IMPLIED
    iterator            CDATA #IMPLIED"
>

<!ELEMENT patterns      (pattern)+>

<!ELEMENT pattern       (%common.elements;)>
<!ATTLIST pattern       name CDATA "main">
  
<!ELEMENT all           (%common.elements;)*>
<!ATTLIST all           %common.attrs;>

<!ELEMENT one           (%common.elements;)*>
<!ATTLIST one           %common.attrs;>

<!ELEMENT opt           (%common.elements;)*>
<!ATTLIST opt           %common.attrs;>

<!ELEMENT some          (%common.elements;)*>
<!ATTLIST some          %common.attrs;>
  
<!ELEMENT attr          (#PCDATA)>
<!ATTLIST attr          %common.attrs; %attr.attrs;>

<!ELEMENT alias         (attr*)>
<!ATTLIST alias         %common.attrs; %attr.attrs;>

<!ELEMENT key_attr      (%common.elements;)*>
<!ATTLIST key_attr      %common.attrs; %attr.attrs;>

<!ELEMENT node_attr     (%common.elements;)*>
<!ATTLIST node_attr     %common.attrs;
    iterator    CDATA #IMPLIED
    attr        CDATA #IMPLIED
>

=== olivergondza/MapFilter_TreePattern/tests/sources/location.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pattern SYSTEM "TreePattern053.dtd">
<pattern>
  <all>
    <attr>action</attr>

    <one>
      <attr>nick</attr>

      <all>
        <attr>x</attr>
        <attr>y</attr>
        <attr>z</attr>
      </all>
    </one>
  </all>
</pattern>

=== olivergondza/MapFilter_TreePattern/tests/new.sources/cat.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE patterns SYSTEM "TreePattern053.dtd">
<patterns>
  <pattern>
    <all>
      <one>

        <key flag="show_help" name="help" />
        
        <key flag="show_version" name="version" />

        <some flag="perform_action">

          <!-- ignote option and set assert if present -->
          <alias attr="u" validationAssert="deprecated" valuePattern="/(?!)/" />

          <!-- translate long options to its short versions -->
          <alias attr="number-nonblank">
            <attr>b</attr>
          </alias>

          <alias attr="show-ends">
            <attr>E</attr>
          </alias>

          <alias attr="number">
            <attr>n</attr>
          </alias>

          <alias attr="squeeze-blank">
            <attr>s</attr>
          </alias>

          <alias attr="show-tabs">
            <attr>T</attr>
          </alias>

          <alias attr="show-nonprinting">
            <attr>v</attr>
          </alias>

          <!-- expand aggregative options -->
          <alias attr="show-all">
            <attr>v</attr>
            <attr>E</attr>
            <attr>T</attr>
          </alias>
          
          <alias attr="A">
            <attr>v</attr>
            <attr>E</attr>
            <attr>T</attr>
          </alias>

          <alias attr="e">
            <attr>v</attr>
            <attr>E</attr>
          </alias>

          <alias attr="t">
            <attr>v</attr>
            <attr>T</attr>
          </alias>

          <!-- allowed short options -->
          <key name="b" />
          <key name="E" />
          <key name="n" />
          <key name="s" />
          <key name="T" />
          <key name="v" />
        </some>  

      </one>
    </all>
  </pattern>
</patterns>

=== olivergondza/MapFilter_TreePattern/tests/sources/filter.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pattern SYSTEM "TreePattern053.dtd">
<pattern>
  <one>

    <attr>-h</attr>
    <attr>-v</attr>

    <some>
      <attr>-c</attr>
      <attr>-l</attr>
    </some>

    <attr>-a</attr>

  </one>
</pattern>

=== olivergondza/MapFilter_TreePattern/tests/sources/direction.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE patterns SYSTEM "TreePattern053.dtd">
<patterns>

  <pattern>
    <some>
      <one>
        <node_attr attr="north" attachPattern="distance" />
        <node_attr attr="south" attachPattern="distance" />
      </one>
      <one>
        <node_attr attr="east" attachPattern="distance" />
        <node_attr attr="west" attachPattern="distance" />
      </one>
    </some>
  </pattern>

  <pattern name="distance">
    <all>
      <attr valuePattern="\d*">count</attr>
      <attr valuePattern="meter|yard">unit</attr>
    </all>
  </pattern>

</patterns>

=== olivergondza/MapFilter_TreePattern/tests/sources/pathway.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE patterns SYSTEM "TreePattern053.dtd">
<patterns>
  <pattern>
    <node_attr attr="steps" iterator="yes">
      <one>
        <attr valuePattern="left|right">turn</attr>
        <node_attr attr="walk">
          <one>
            <attr valuePattern="\d*">metres</attr>
            <attr valuePattern="\d*">yards</attr>
          </one>
        </node_attr>
      </one>
    </node_attr>
  </pattern>
</patterns>

=== olivergondza/MapFilter_TreePattern/tests/sources/login.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pattern SYSTEM "TreePattern053.dtd">
<pattern>
  <all flag="login">

    <attr assert="no_name">name</attr>
    <attr assert="no_password">pass</attr>

    <opt>

      <attr flag="use_https" valuePattern="yes">use-https</attr>
      <all flag="remember">

        <attr>remember</attr>
        <one assert="no_remember_method">

          <attr>user</attr>
          <attr>server</attr>

        </one>

      </all>

    </opt>

  </all>
</pattern>
